### ISSUE TITLE
Compatibility with datatables 2.0

### ISSUE THREAD

**Issue by aureltime** [vedmack/yadcf#681]
Hello Daniel,

do you plan to make yadcf compatible with datatables 2.0 ?

**Comment by VictorioBerra** [comment]
See https://github.com/vedmack/yadcf/issues/680

CC @vedmack

**Comment by aureltime** [comment]
thanks for the link, i close this one to avoid duplicate

**Comment by vedmack** [comment]
@aureltime Yes I am, see this test page for example https://jsfiddle.net/vedmack/8bur71tk/
The current yadcf version that supports DT 2 is yadcf 2.0.1.beta.3

Feel free to provide test pages so I can apply the required modification faster

**Comment by vedmack** [comment]
new showcase page https://yadcf.web.app

**Comment by berndy2001** [comment]
Hello Daniel,

thank you for the update.

In the showcase DT 2.0.0 is used; with a newer version (2.0.8) an error occurs, see fiddle
https://jsfiddle.net/msuo0e14/

```
"jQuery.Deferred exception: Cannot read properties of undefined (reading 'split')", "TypeError: Cannot read properties of undefined (reading 'split')
    at yadcfVersionCheck (https://raw.githack.com/vedmack/yadcf/master/2.0/jquery.dataTables.yadcf-2.0.js:832:49)
```

**Comment by vedmack** [comment]
thx for the report, fixed in 2.0.1.beta.7, you can see here: https://jsfiddle.net/vedmack/gLjrf5ax/. I will update the showcase later on

**Comment by berndy2001** [comment]
When I use the `language` option from datatables, I get an error from yadcf.

```
"jQuery.Deferred exception: Cannot read properties of undefined (reading 'map')", "TypeError: Cannot read properties of undefined (reading 'map')
    at appendFilters (https://raw.githack.com/vedmack/yadcf/refs/heads/master/2.0/jquery.dataTables.yadcf-2.0.js:3282:33)
    at initAndBindTable (https://raw.githack.com/vedmack/yadcf/refs/heads/master/2.0/jquery.dataTables.yadcf-2.0.js:5014:11)
    at Object.init (https://raw.githack.com/vedmack/yadcf/refs/heads/master/2.0/jquery.dataTables.yadcf-2.0.js:5224:11)
    at HTMLDocument.&lt;anonymous&gt; (https://fiddle.jshell.net/_display/?editor_console=true:443:9)
    at e (https://code.jquery.com/jquery-3.6.4.min.js:2:30158)
    at t (https://code.jquery.com/jquery-3.6.4.min.js:2:30460)", undefined
```


With datatables 1.13.5 and yadcf 0.9.4b47 this problem did not occur.

fiddle: https://jsfiddle.net/zc10mgsa/2/

**Comment by berndy2001** [comment]
I found something else strange in DT2.0. If umlauts are used in column_data_type: 'rendered_html', they are lost.

![image](https://github.com/user-attachments/assets/f0b4dab9-00be-490b-b473-14d7a179396f)

example: https://live.datatables.net/bisaxayu/1/edit

**Comment by kainers1** [comment]
Hello @vedmack 

any updates on the two issues?

**Comment by vedmack** [comment]
Actually, yes, it's already here, you can try out the latest yadcf  2.0; it supports DataTables 2.0

https://github.com/vedmack/yadcf/blob/master/2.0/jquery.dataTables.yadcf-2.0.js
